version: '3.8'

services:
  wordpress:
    build: .
    container_name: wordpress
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: localhost
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: passwd
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content

  db:
    image: mariadb:latest  
    container_name: db
    restart: always
    port: 
     - "5432"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: passwd
      MYSQL_ROOT_PASSWORD: root_passwd
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
